services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpass
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src  # Монтируем только исходный код
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

volumes:
  db_data:

